name: Release
on:
  push:
    branches: ["master"]

permissions:
  id-token: write
  contents: write
  pull-requests: write

env:
  HUSKY: 0
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  skip: false

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          ref: master
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          cache: pnpm
          registry-url: https://registry.npmjs.org

      - name: Install modules
        run: pnpm install --no-frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Add Git Config
        run: |
          git config user.name "Potter"
          git config user.email "aa4790139@gmail.com"
          git remote set-url origin https://x-access-token:${{ secrets.TOKEN }}@github.com/artipub/artipub.git

      - name: Compare tag with package.json version
        run: |
          closest_tag=$(git describe --tags --exact-match 2>/dev/null || echo "")
          echo "Closest tag: $closest_tag"
          if [ "$closest_tag" != "" ]; then
            echo "skip=true" >> $GITHUB_ENV
          else
            echo "skip=false" >> $GITHUB_ENV
          fi

      - name: Output skip
        run: |
          echo "skip: $skip"

        # skip = true means skip steps below
      - name: Generate Changelog and Create Release
        if: env.skip == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          pnpm release --no-git-checks

      - name: Commit changes
        if: env.skip == 'false'
        run: |
          git diff --quiet || git commit -am "chore: auto update for release"

      - uses: ad-m/github-push-action@v0.6.0
        if: env.skip == 'false'
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: master

      - name: Set npmrc
        if: env.skip == 'false'
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          echo "@artipub:registry=https://registry.npmjs.org" >> ~/.npmrc
          echo "always-auth=true" >> ~/.npmrc

      - uses: actions/setup-node@v4
        if: env.skip == 'false'
        with:
          node-version: "20.x"
          # Note: Registration-url must be set here, otherwise the permissions will be wrong
          registry-url: "https://registry.npmjs.org"
          scope: "@artipub"

      - name: Publish package
        if: env.skip == 'false'
        run: pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
